### ISSUE TITLE
 Cannot read property 'updated' of null

### ISSUE THREAD

**Issue by ynnoj** [EmberSherpa/fastboot-gcloud#2]
Hey! Been following [this](https://blog.embersherpa.com/easy-ember-fastboot-deployment-with-google-cloud-216160afe2b8) guide to deploy a FastBoot app to a Google Cloud project.

However the `gcloud app deploy` process is timing out. Looking at the logs it looks as though the `fastboot-gcloud-storage-notifier` dependency is tripping up.

```
TypeError: Cannot read property 'updated' of null
at /app/node_modules/fastboot-gcloud-storage-notifier/index.js:32:30
at /app/node_modules/gcloud/lib/common/service-object.js:219:7
at /app/node_modules/gcloud/lib/common/service-object.js:248:7
at Object.handleResp (/app/node_modules/gcloud/lib/common/util.js:126:3)
at /app/node_modules/gcloud/lib/common/util.js:446:12
at Request.onResponse [as _callback] (/app/node_modules/retry-request/index.js:120:7)
at Request.self.callback (/app/node_modules/request/request.js:186:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/app/node_modules/request/request.js:1081:10)
```

**Comment by ynnoj** [comment]
Turns out I had the wrong project name in my deploy config 😑
